name: wastemanagement
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2
  get_it: ^8.0.3
  google_sign_in: ^6.2.2
  dio: ^5.8.0+1
  flutter_bloc: ^9.0.0
  dartz: ^0.10.1
  connectivity_plus: ^6.1.3
  permission_handler: ^11.4.0
  pretty_dio_logger: ^1.4.0
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  fluttertoast: ^8.2.12
  http: ^1.3.0
  image_picker: ^1.1.2
  uuid: ^4.5.1
  latlong2: ^0.9.1
  flutter_map: ^8.0.0
  sensors_plus: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.3.3
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
